### Exceptions init
Pymata4 will raise a RuntimeError exception in \__init__ for the following reasons:

1. Python version being using is not Python 3.7 or higher.
2. Auto-discovery fails for any reason.
3. The user hit Control-C.



<br>
<br>

Copyright (C) 2020 Alan Yorinks. All Rights Reserved.
